server:
  port: 8080

spring:
  datasource:
    username: user
    password: pass
    url: jdbc:mysql://localhost:3306/cities_and_sights?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: create-drop
    show-sql: true